# Config for flowcell reports

run_modules:
    - fastqc
    - fastq_screen
    - bclconvert
    - interop
    - custom_content

table_columns_visible:
    FastQC:
        percent_duplicates: False
        percent_gc: False
        total_sequences: False

top_modules:
    - 'custom_content'
    - 'bclconvert'
    - 'interop'

